# Set up a user and SFTP-only group
# Create directories for download of reports
# SFTP_user_password must be set in server-vars.yml
# set up cronjobs for custom ISC reports

- hosts: "edxapp-server"
  sudo: true
  vars:
    sftp_users: 
      iscreportsftp:
        pwd: "{{ ISC_SFTP_user_password }}"
        reports_dir: "course_participation"
      cmcreportsftp: 
        pwd: "{{ CMC_SFTP_user_password }}"
        reports_dir: "cmc_reports"

    sftp_group: "filetransfer"
  tasks:
    - include_vars: "/edx/app/edx_ansible/edx_ansible/playbooks/roles/common/defaults/main.yml"

    - name: create SFTP group
      group: name={{ sftp_group }} state=present

    - name: create SFTP users
      user: "name={{ item.key }} password={{item.value.pwd}} groups={{ sftp_group }} shell=/sbin/nologin createhome=yes"
      with_dict: sftp_users


    - name: change owner of SFTP user home dir to root
      file: >
        path="/home/{{ item.key }}"
        owner="root"
        state="directory"
      with_dict: sftp_users

    - name: make reports subdirectories
      file: >
        path="/home/{{ item.key }}/{{ item.value.reports_dir }}"
        state=directory
        owner={{ item.key }}
        group=edxapp
        mode=0755
      with_dict: sftp_users 

  # would rather use blockinfile here but not present < ansible 2.0
  # these aren't working on GCloud VM and will kill your sshd and you will be locked out.
  # TODO: FIXME.  try lineinfile validate command, and sshd -t to test the config before restarting sshd
    - name: Update sshd config to force SFTP group to chrooted internal-sftp only
      sudo: True
      lineinfile: 
        dest: /etc/ssh/sshd_config
        line: "{{ item }}"
        validate: "sshd -t -f %s"
        backup: yes
      with_items: 
        - Match group {{sftp_group}}
        -   PasswordAuthentication yes
        -   ChrootDirectory %h
        -   X11Forwarding no
        -   AllowTcpForwarding no
        -   ForceCommand internal-sftp

    - name: check sshd config
      sudo: True
      shell: sshd -t
      register: sshd_check

    - debug: msg="This output of sshd -t should be empty... {{ sshd_check }}"

    - name: restart ssh
      service: name=ssh state=restarted
      sudo: True
      when: sshd_check.stdout == ""


    - name: cron job for generating reports
      cron: >
        user=root
        name="{{ item.value.name }}"
        job="{{ item.value.cmd }}"
        minute="{{ item.value.minute }}"
        hour="{{ item.value.hour }}"
      with_dict: {
        "cmc": {
          "name": "ISC CMC course completion and access report every morning 8:00PM GMT",
          "minute": 0,
          "hour": 20,
          "cmd": "/edx/app/edxapp/venvs/edxapp/bin/python /edx/app/edxapp/edx-platform/manage.py lms cmc_course_completion --settings=aws > /dev/null 2>&1"
        },
        "va": {
          "name": "ISC VA Learning Path enrollment report every morning 1:00AM ET",
          "minute": 0,
          "hour": 6,
          "cmd": "/edx/app/edxapp/venvs/edxapp/bin/python /edx/app/edxapp/edx-platform/manage.py lms va_enrollment_status --settings=aws > /dev/null 2>&1"
        },
        "isc_daily": {
          "name": "ISC all-course participation report every morning 1:05AM ET",
          "minute": 5,
          "hour": 6,
          "cmd": "/edx/app/edxapp/venvs/edxapp/bin/python /edx/app/edxapp/edx-platform/manage.py lms isc_course_participation --settings=aws > /dev/null 2>&1"
        }
      }

    - name: cron job for cleaning out old reports
      cron: >
        user=root
        name="Remove {{item.value.reports_dir}} csv files older than 7 days, each time after the report is run"
        job="find /home/{{ item.key }}/{{ item.value.reports_dir }}/ -mtime +7 -exec rm {} \;"
        minute="10"
        hour="20"
      with_dict: sftp_users 


